services:
  frontend:
    container_name: softskills-frontend
    restart: always
    build:
      context: ./soft-skills-frontend
      dockerfile: ./Dockerfile
    env_file: ./soft-skills-frontend/.env
    ports:
      - "127.0.0.1:80:80"
    depends_on:
      - backend
    networks:
      - server-network

  backend:
    container_name: softskills-backend
    restart: always
    build:
      context: ./soft-skills-school-api
      dockerfile: ./Dockerfile
    env_file: ./soft-skills-school-api/.env
    ports:
      - "127.0.0.1:3000:8080"
    depends_on:
      - db
    networks:
      - server-network

  db:
    container_name: softskills-db
    image: mongo:latest
    restart: always
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
    - mongo-data:/var/lib/mongodb
    networks:
      - server-network

networks:
  server-network:
    driver: bridge

volumes:
  mongo-data:
    external: false

  # docker-compose up --force-recreate --build --no-cache -d 